### ISSUE TITLE
Applying to add a paper to this paper list about this topic

### ISSUE THREAD

**Issue by Luoxd1996** [LightersWang/Awesome-Active-Learning-for-Medical-Image-Analysis#1]
Hi,
Great job, thanks for your teams' efforts. There is relevant work using active learning and source-free domain adaptation for tumor delineation across multiple hospitals, which may be met this topic. [Arxiv2023](https://arxiv.org/pdf/2309.13401.pdf).
Best,
Xiangde Luo.

**Comment by LightersWang** [comment]
Hi Xiangde,
Thanks for your suggestion! This paper is added to the repo.
Also, if you find this repo helpful, please star us!

Best Regards,
Haoran Wang
