### ISSUE TITLE
Wrong link，can you update

### ISSUE THREAD

**Issue by Dog-Yang** [LightersWang/Awesome-Active-Learning-for-Medical-Image-Analysis#4]
Hi, nice work,

In code/classification, the ISIC 2020 data set in the Medical Datasets Supported you provided is a wrong link, can you update it?

Thank you for your outstanding work！！

**Comment by Dog-Yang** [comment]
Hello, I have another question

It is recommended to resize each image to 300x300 for faster speeds.
Does this operation require the developer to resize the data set with a script？

Looking forward to your reply

**Comment by LightersWang** [comment]
Thanks for your feedback! I'll let you know when I fix these things.

**Comment by Dog-Yang** [comment]
thanks！！

**Comment by LightersWang** [comment]
Hi, the ISIC website issue is fixed and the image resizing script is uploaded, please refer to the source code.
